// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using OrderResponse;
//
//    var orderResponse = OrderResponse.FromJson(jsonString);

namespace Response.CreateOrderResult
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    /// Класс Результат создания заказа(отправления)
    /// </summary>
    public partial class CreateOrderResult
    {
        /// <summary>
        /// Список ошибок
        /// </summary>
        [JsonProperty("errors", NullValueHandling = NullValueHandling.Ignore)]
        public Error[] Errors { get; set; }

        /// <summary>
        /// Список внутрених идентификаторов заказов (Id) успешно обработанных
        /// </summary>
        [JsonProperty("result-ids", NullValueHandling = NullValueHandling.Ignore)]
        public long[] ResultIds { get; set; }
    }

    /// <summary>
    /// Ошибка
    /// </summary>
    public partial class Error
    {
        /// <summary>
        /// Список кодов ошибок
        /// </summary>
        [JsonProperty("error-codes", NullValueHandling = NullValueHandling.Ignore)]
        public ErrorCode[] ErrorCodes { get; set; }

        /// <summary>
        /// Индекс ошибочной записи в массиве Заказов(Отправлений)
        /// </summary>
        [JsonProperty("position", NullValueHandling = NullValueHandling.Ignore)]
        public long? Position { get; set; }
    }

    /// <summary>
    /// Код ошибки
    /// </summary>
    public partial class ErrorCode
    {
        /// <summary>
        /// Код: "UNDEFINED",...
        /// см. https://otpravka.pochta.ru/specification#/enums-errors
        /// </summary>
        [JsonProperty("code", NullValueHandling = NullValueHandling.Ignore)]
        public string Code { get; set; }

        /// <summary>
        /// Описание ошибки (Опционально)
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description { get; set; }

        /// <summary>
        /// Подробности (Опционально)
        /// </summary>
        [JsonProperty("details", NullValueHandling = NullValueHandling.Ignore)]
        public string Details { get; set; }

        /// <summary>
        /// Индекс в массиве (Опционально)
        /// </summary>
        [JsonProperty("position", NullValueHandling = NullValueHandling.Ignore)]
        public long? Position { get; set; }
    }

    public partial class CreateOrderResult
    {
        public static CreateOrderResult FromJson(string json) => JsonConvert.DeserializeObject<CreateOrderResult>(json, Response.CreateOrderResult.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this CreateOrderResult self) => JsonConvert.SerializeObject(self, Response.CreateOrderResult.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
