// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Request.PhoneRequest;
//
//    var phoneRequest = PhoneRequest.FromJson(jsonString);

namespace Request.PhoneRequest
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class PhoneRequest
    {
        [JsonProperty("area", NullValueHandling = NullValueHandling.Ignore)]
        public string Area { get; set; }

        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        [JsonProperty("original-phone", NullValueHandling = NullValueHandling.Ignore)]
        public string OriginalPhone { get; set; }

        [JsonProperty("place", NullValueHandling = NullValueHandling.Ignore)]
        public string Place { get; set; }

        [JsonProperty("region", NullValueHandling = NullValueHandling.Ignore)]
        public string Region { get; set; }
    }

    public partial class PhoneRequest
    {
        public static PhoneRequest[] FromJson(string json) => JsonConvert.DeserializeObject<PhoneRequest[]>(json, Request.PhoneRequest.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this PhoneRequest[] self) => JsonConvert.SerializeObject(self, Request.PhoneRequest.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
